### PR TITLE
[WIP] Adding first pass of the merck_hinge_simple set

### PR DESCRIPTION
**Pull request by Lnaden**
cc @jchodera

### CODE REVIEW

**Comment by jchodera** [comment]
Can we rename the directory to be something like `c-Met-hinge-binders`? I want to avoid the implication that we may accidentally be putting Merck proprietary data somewhere.

**Comment by jchodera** [comment]
Directory structure looks much nicer, thanks!

**Comment by Lnaden** [comment]
Sure, once I am done making sure everything works, I'll touch up some of the names and whatnot, Also note to self is cite the paper its from.

**Comment by jchodera** [comment]
Other than renaming the directory from `merck_hinge_binders`, this looks really good to me!

**Comment by Lnaden** [comment]
Ah, I misinterpreted the rename. I changed `_dataset` to `_binders`, it was the "`merck`" part. Will change

**Comment by jchodera** [comment]
Thanks. I want to avoid the implication that we may accidentally be putting Merck proprietary data somewhere.

**Pull request merged**
